# This file goes in the root of your repository

[build]
  base    = "frontend"      # Change directory to 'frontend' before building
  command = "npm run build" # The build command
  publish = "dist" # The folder to deploy (relative to the root)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
